@startuml
'https://plantuml.com/class-diagram

class Game {

}

class HeroAircraft {
    - {static} heroAircraft : HeroAircraft

    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp, int shootNum, int power, int shootDirection, ShootStrategy shootStrategy)
    + {static} getHeroAircraft(): HeroAircraft
    + forward(): void
}

HeroAircraft::heroAircraft --> HeroAircraft

Game -right-> HeroAircraft::getHeroAircraft

@enduml