@startuml
'https://plantuml.com/class-diagram

Game ..> PropsFactory
Game ..> AbstractProps

PropsFactory ..> AbstractProps

PropsFactory <|.. BloodFactory
PropsFactory <|.. BombFactory
PropsFactory <|.. BulletFactory

AbstractProps <|-- BloodProps
AbstractProps <|-- BombProps
AbstractProps <|-- BulletProps

BloodFactory  ..> BloodProps
BombFactory   ..> BombProps
BulletFactory ..> BulletProps

class Game {

}

interface PropsFactory {
    + createProps(int locationX, int locationY, int speedX, int speedY, int hp): List<AbstractProps>
}

class BloodFactory {
    - props: List<AbstractProps>
    + BloodFactory()
    + createProps(int locationX, int locationY, int speedX, int speedY, int hp): List<AbstractProps>
}

class BombFactory {
    - props: List<AbstractProps>
    + BombFactory()
    + createProps(int locationX, int locationY, int speedX, int speedY, int hp): List<AbstractProps>
}

class BulletFactory {
    - props: List<AbstractProps>
    + BulletFactory()
    + createProps(int locationX, int locationY, int speedX, int speedY, int hp): List<AbstractProps>
}

abstract class AbstractProps {

    + AbstractProps(int locationX, int locationY, int speedX, int speedY)
    + forward(): void
}

class BloodProps {
    -treatment: int

    + HpProps(int locationX, int locationY, int speedX, int speedY)
    + getTreatment(): int
}

class BombProps {

    + BombProps(int locationX, int locationY, int speedX, int speedY)
}

class BulletProps {

    + FireProps(int locationX, int locationY, int speedX, int speedY)
}

@enduml